### ISSUE TITLE
Remove message

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#80] opened 2019-03-12 17:31 UTC
This is not a major thing, but when I run qkinc the following message appears repeatedly in the terminal:

> Attempting to write a log message when logging is disabled!

Can we remove that?

**Comment by bentsherman** [comment] 2019-04-02 16:42
That's probably a question for @4ctrl-alt-del

**Comment by 4ctrl-alt-del** [comment] 2019-04-02 17:38
@bentsherman that message is triggered if you attempt to write a log message without checking to see if it is enabled. ACE does not make a single log message therefore you must be doing that somewhere in KINC. Remember that ELog::isActive() must be checked before writing any log message. I designed it this way to make ACE more efficient if logging is disabled.

**Comment by bentsherman** [comment] 2019-04-02 19:58
Well that's odd, I checked and all of the log messages in KINC have that pre-condition so I don't know. @spficklin make sure you have the latest updates? Although I haven't messed with those messages in a while. If you could share any other messages that are logged that would be helpful.

**Comment by bentsherman** [comment] 2019-06-17 15:19
Closing since I can't reproduce this log message.

**Closed as completed by bentsherman** 2019-06-17 15:19 UTC
