### ISSUE TITLE
-1 values in RMT run

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#85] opened 2019-05-11 04:58 UTC
Hey, I'm getting -1 values in the RMT correlation log and I don't know where to set the threshold.  See the following:
```
0.910001        1040    100.379
0.909001        1065    -1
0.908001        1087    90.0595
0.907001        1121    104.523
0.906001        1148    -1
0.905001        1184    -1
0.904001        1225    -1
0.903001        1267    -1
0.902001        1298    -1
0.901001        1325    -1
0.900001        1361    -1
0.899001        1400    -1
0.898001        1444    -1
0.897001        1479    -1
0.896001        1509    -1
0.895001        1540    -1
0.894001        1578    -1
0.893001        1614    -1
0.892001        1658    -1
0.891001        1702    -1
0.890001        1747    -1
0.889001        1790    -1
0.888001        1824    -1
0.887001        1871    -1
0.886001        1915    -1
0.885001        1956    -1
0.884001        2001    -1
0.883001        2050    -1
0.882001        2097    -1
0.881001        2141    -1
0.880001        2185    -1
0.879001        2224    -1
0.878001        2285    -1
0.877001        2331    -1
0.876001        2380    -1
0.875001        2438    -1
0.874001        2490    -1
0.873001        2551    -1
0.872001        2620    -1
0.871001        2681    -1
0.870001        2732    -1
0.869001        2796    -1
0.868001        2850    197.069
0.867001        2917    179.599
0.866001        2970    206.221
0.908001
```
I could cut at 0.9 but there could be another dip below 100 that I can't see because of the -1's.

**Comment by bentsherman** [comment] 2019-05-14 14:41
My best guess is that the number of unique eigenvalues is falling below the minimum, which is 50 by default. Do you have the console log of this RMT run? It shows the number of unique eigenvalues for each threshold but it doesn't print them to the log file. I will go ahead and update RMT to include this information in the log file.

**Comment by bentsherman** [comment] 2019-10-22 16:13
This issue is a duplicate of #86, closing.

**Closed as completed by bentsherman** 2019-10-22 16:13 UTC
